[package]
name = "file-viewer-core"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
directories = { workspace = true }

